[config]

fallback_color = "#ffbf9b"

prefer = "saturation"

# caching = true

[config.wallpaper]
# Whether to set the wallpaper or not
set = true

# The base command to run for applying the wallpaper.
# Keywords like {{ image }} or anything that works inside of hooks works here.
command = "/home/sam/.config/hypr/hyprpaper/switchhyprpaper.sh"

# For example, killing the wallpaper daemon. Usage is like a normal hook.
# pre_hook = ""

[templates.waybar]
input_path = '~/.config/matugen/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = "pkill -SIGUSR2 waybar"

[templates.wlogout]
input_path = '~/.config/matugen/colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.wofi]
input_path = '~/.config/matugen/colors.css'
output_path = '~/.config/wofi/colors.css'

[templates.kitty]
input_path = '~/.config/matugen/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"
